### PR TITLE
Merge Fixes for physical test

### LINKED ISSUE #44: Fix physical tests
The physical tests have some known issues and room for improvement.   
- the point state is not recorded correctly: the point is switched and immediately afterwards its state is sampled. At that point, we haven't had time to receive the feedback from the corresponding control board on the execution state of the point.
- memory is not always freed correctly.
- tests with train driving: after we set the points, we don't check if they are in the expected position -> if a point is not working correctly, we'll likely get a short circuit.
- we could use some more documentation and perhaps debugging info, for example the track output and booster state when the SIGINT callback is triggered, i.e., if we manually abort a test.

Work on this has already begun in branch fix-physical-test.

### PR DESCRIPTION
**Pull request by BLuedtke**
Closes #44 

Currently a draft as we have to actually run these improved physical tests still.

Note: there's a fix contained in that branch for historical reasons, which is about a compiler warning wrt. a potentially uninitialized var.

### CODE REVIEW

File: test/physical/test_common.c [hunk 1]
```diff
@@ -114,14 +119,22 @@ void testsuite_stopBidib(void) {
...
+	printf("   Track output states:\n");
+	testsuite_logAllTrackOutputStates();
+	printf("\n");
+	printf("   Booster power states:\n");
+	testsuite_logAllBoosterPowerStates();
+	printf("\n");
+	printf("testsuite: SIG %d - now stopping libbidib.\n", signum);
 	testsuite_stopBidib();
-	printf("testsuite: SIGINT - stopping libbidib \n");
+	printf("testsuite: SIG %d - libbidib stopped.\n", signum);
```
Comment (eyip002) [inline test/physical/test_common.c]: Instead of printing the signal code, you could use `strsignal` or `sys_signame` to print the signal name: https://stackoverflow.com/a/16509837

File: test/physical/swtbahn-standard/testsuite.c [hunk 2]
```diff
@@ -125,25 +135,74 @@ void testsuite_case_swtbahnStandardTrackCoverage(const char *train) {
...
+	point_check &= testsuite_check_point_aspect("point6", "reverse");
+	point_check &= testsuite_check_point_aspect("point8", "reverse");
+	point_check &= testsuite_check_point_aspect("point2", "reverse");
+	point_check &= testsuite_check_point_aspect("point3", "reverse");
+	point_check &= testsuite_check_point_aspect("point4", "reverse");
+	point_check &= testsuite_check_point_aspect("point5", "reverse");
+	point_check &= testsuite_check_point_aspect("point12", "normal");
+	point_check &= testsuite_check_point_aspect("point10", "reverse");
+	point_check &= testsuite_check_point_aspect("point9", "reverse");
+	point_check &= testsuite_check_point_aspect("point11", "reverse");
```
Comment (eyip002) [inline test/physical/swtbahn-standard/testsuite.c]: Seems like a helper function should be defined that does the switching and checking of points: it takes a list of points and a corresponding  list of aspects, it calls `testsuite_switch_point` on each pair of point-aspect, it sleeps for `POINT_WAITING_TIME_S` seconds, and then it calls  `testsuite_check_point_aspect` on each pair of point-aspect.

File: test/physical/test_common.c [hunk 3]
```diff
@@ -276,37 +351,137 @@ void testsuite_case_signal_common(char **aspects, size_t aspects_len) {
...
+			t_bidib_unified_accessory_state_query state = bidib_get_point_state(points.ids[i-1]);
+			testsuite_recordTestResult(result, state, i-1);
+			bidib_free_unified_accessory_state_query(state);
+		}
 		sleep(POINT_WAITING_TIME_S);
 	}
 }
+
+const char * const testsuite_cs_state_str[] = {
+	[BIDIB_CS_OFF] = "BIDIB_CS_OFF",
```
Comment (eyip002) [inline test/physical/test_common.c:469]: I learnt some new C syntax 😆

**Comment by eyip002** [comment]
I know that this is just a draft, but I left a few comments

File: test/physical/swtbahn-standard/testsuite.c (hunk 2 above)
Comment (BLuedtke) [reply test/physical/swtbahn-standard/testsuite.c]: Absolutely. I've done something like that when I implemented the physical tests in libbidib-cpp.   
The reason I haven't done it here is that I don't really want to malloc all that stuff; and whilst it is technically possible to do it just statically (as the strings are all known already), I don't remember how to do that correctly when arrays of strings are involved, from a syntax standpoint 😅 .

Comment (BLuedtke) [reply test/physical/swtbahn-standard/testsuite.c]: Oh. It's much easier than I expected! Good news. As there are only 2 aspects, that part doesnt even need to be a parameter.

**Comment by BLuedtke** [comment]
I finally found something wrt. the temporary lockups. And that is: the systemd journald `SyncIntervalSec`. The default is 5 minutes. If I set it 20 seconds and restart, I see problems/delays roughly every 20s. So maybe this is it? Syncing logs to disc being the bottleneck would not surprise me, given that this is syncing to an SD-card.

Based on the configuration options described in [here](https://www.freedesktop.org/software/systemd/man/latest/journald.conf.html), I'll test some optimizations while keeping the sync interval to 20s.
- turning off compression and sealing to reduce effort per sync: complete disaster, everything is extremely delayed
- **turning off persistent storage completely (`storage=volatile`): works very reliably, no freezes at all. Syslog also seems to be more responsive. tested >10 runs.** 🥳 🥳 
   - note that this does not disable the syslog from being persisted to a file. It just disables the periodic journal from being persisted, this journal seems to include all syslog messages, and is apparently much more expensive to save than the usual syslog logs. IMO this can be turned off no problem.



Regarding the experimental observer I added, it is working well (with no noticable overhead). However, now that the freezes are pretty much gone, its unclear if its really needed anymore. I'll probably keep it and add the observing to the other parts of the physical test.

**Comment by eyip002** [comment]
> * **turning off persistent storage completely (`storage=volatile`): works very reliably, no freezes at all. Syslog also seems to be more responsive. tested >10 runs.** 🥳 🥳

Nice find!

File: test/physical/test_common.c (hunk 1 above)
Comment (BLuedtke) [reply test/physical/test_common.c]: currently trying to do this, but ATM I can't get any of the proposed methods to work. Even if I include signal.h, `sys_signame` is not available.

Comment (BLuedtke) [reply test/physical/test_common.c]: Works with `strsignal`, but not with `sigabbrev_np` - something to do with GNU extensions I guess. Tried to enable them via CMake, but to no avail. `strsignal` should suffice though, we are not calling it from multiple threads anyway.

Comment (BLuedtke) [reply test/physical/test_common.c]: Ah, but we are calling that signal handler with signal -1 ourselves from the occupancy observer. The idea was to use the signal handler there, because then the shutdown is always done the same way, regardless of whether we get SIGINT from outside (ctrl+c) or terminate because a train has been observed in an illegal position. I'll add a corresponding conditional to deal with this.

File: test/physical/swtbahn-standard/testsuite.c (hunk 2 above)
Comment (BLuedtke) [reply test/physical/swtbahn-standard/testsuite.c]: Done.

**Comment by BLuedtke** [comment]
Ready for review. I still have to actually run the updated tests on the platforms.

**Review by eyip002 — DISMISSED** [review]
Changes look good and I'm sure you've tested it well. Ready for you to merge!

File: test/physical/test_common.c [hunk 4]
```diff
@@ -261,9 +261,24 @@ void testsuite_driveTo(const char *segment, int speed, const char *train) {
...
+			//    a) the train ID hasn't been broadcasted on this segment yet (~0.3s delay common)
+			//    b) the train has been lost but the occupancy detection (detecting *something*)
+			//       still works.
+			// Scenario a will probably be more common and it is difficult to distinguish between 
+			// the two scenarios. For now, we just log this case and see if we learn something
+			// during test execution.
+			struct timespec tv;
+			clock_gettime(CLOCK_MONOTONIC, &tv);
+			printf("testsuite: drive %s to %s at speed %d - "
+			       "segment is occupied, but train not detected on it, time %ld.%.ld\n",
```
Comment (eyip002) [inline test/physical/test_common.c]: Is there an extra `.` in the time format? 
`%ld.%.ld` --> `%ld.%ld`
and the nanoseconds should be converted to milliseconds?
Check for other instances of this

**Review by eyip002 — COMMENTED** [review]
I'm not sure if you've finished testing the tests or not ...

**Comment by BLuedtke** [comment]
> I'm not sure if you've finished testing the tests or not ...

Well, there were some smaller problems; I hadn't yet been able to completely test everything for the SWTbahn-Full when you reviewed it, sorry. I'll be completing this soon.

File: test/physical/test_common.c (hunk 4 above)
Comment (BLuedtke) [reply test/physical/test_common.c]: mmh, interesting. It looks like this occurs multiple times - either for a good reason or just copy-paste mistakes. I'll investigate.

Comment (BLuedtke) [reply test/physical/test_common.c]: Ah, the `.` is a leftover from me trying to control how many places were printed. Doesn't do anything as it is, so will be removed.

I've added a format specified (`%09ld`) that makes sure we print 9 digits. E.g., if only 500 nanoseconds have passed in the current second, then the old code would print:    
`123.500`    
Which is misleading, because it looks like half a second even though its only 500 ns.    
With the update I'll be pushing, it would print:    
`123.000000500`

I'll also test reducing the nanoseconds to microseconds to make it a bit easier to read. Milliseconds might be too low precision sometimes.

**Comment by BLuedtke** [comment]
I'll test this - hopefully later today. If that goes as planned, this is finally done.

**Comment by BLuedtke** [comment]
Tested, with multiple trains, all the test cases, etc., also with one of the new trains (perso_sbb). After the adjustments, it works quite well.    
I think the tracks were a little dirty initially - I had a few cases where a train drove over a segment and only triggered BM_OCC, not BM_ADDRESS, i.e., the train id was not recognized. I was unable to reproduce this however. 

I noticed that the locos with newer decoders (cargo_bayern, perso_sbb) performed a little better - at least they felt more responsive, i.e., they were quicker to be recognized as occupying a segment.
